// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmklubb_backend.Data;

#nullable disable

namespace filmklubb_backend.Migrations
{
    [DbContext(typeof(FilmklubbContext))]
    [Migration("20260915075432_SeedFlerFilmer")]
    partial class SeedFlerFilmer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("filmklubb_backend.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Watched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Bäst på stor duk. Ljudmixen bär hela filmen.",
                            Rating = 5,
                            Title = "Dune: Part Two",
                            Type = "Film",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 1, 18, 20, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 12, 9, 15, 0, 0, DateTimeKind.Utc),
                            Notes = "Säsong 1 håller hela vägen. Långsam start.",
                            Rating = 4,
                            Title = "Severance",
                            Type = "Serie",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 2, 2, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Tre och en halv timme - boka in en hel kväll.",
                            Title = "The Brutalist",
                            Type = "Film",
                            Watched = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            Title = "Shogun",
                            Type = "Serie",
                            Watched = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 9, 8, 15, 0, 0, DateTimeKind.Utc),
                            Notes = "Grym story, ännu bättre score",
                            Title = "Interstellar",
                            Type = "Serie",
                            Watched = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 2, 19, 30, 0, 0, DateTimeKind.Utc),
                            Notes = "Spara till en mörk kväll.",
                            Title = "Nosferatu",
                            Type = "Film",
                            Watched = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Stressig på ett bra sätt. Kolla inte på tom mage.",
                            Rating = 5,
                            Title = "The Bear",
                            Type = "Serie",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 4, 1, 22, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 8, 16, 45, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Past Lives",
                            Type = "Film",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 4, 20, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sägs vara bra även om man skiter i Star Wars.",
                            Title = "Andor",
                            Type = "Serie",
                            Watched = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 22, 13, 20, 0, 0, DateTimeKind.Utc),
                            Notes = "Snyggast i år, men lite för lång.",
                            Rating = 3,
                            Title = "Poor Things",
                            Type = "Film",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 6, 2, 21, 30, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
