// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmklubb_backend.Data;

#nullable disable

namespace filmklubb_backend.Migrations
{
    [DbContext(typeof(FilmklubbContext))]
    partial class FilmklubbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("filmklubb_backend.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Watched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Bäst på stor duk. Ljudmixen bär hela filmen.",
                            Rating = 5,
                            Title = "Dune: Part Two",
                            Type = "Film",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 1, 18, 20, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 12, 9, 15, 0, 0, DateTimeKind.Utc),
                            Notes = "Säsong 1 håller hela vägen. Långsam start.",
                            Rating = 4,
                            Title = "Severance",
                            Type = "Serie",
                            Watched = true,
                            WatchedAt = new DateTime(2026, 2, 2, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Tre och en halv timme - boka in en hel kväll.",
                            Title = "The Brutalist",
                            Type = "Film",
                            Watched = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            Title = "Shogun",
                            Type = "Serie",
                            Watched = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
